In [ ]:
# LogisticRegression Model ---- > when our target data is categorical .
# LogisticRegression Model --- > backend --- > 1 Activation function(Sigmoid) --- > Based on Probability --- >
# threshold_value = 0.5
# if x>0.5:
#   return 1
# else:
#   return 0

In [46]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [48]:
# df.isnull().sum()

In [49]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [50]:
from sklearn.preprocessing import LabelEncoder

In [51]:
le = LabelEncoder()

In [52]:
df['gender'] = le.fit_transform(df['gender'])
df['cough'] = le.fit_transform(df['cough'])
df['city'] = le.fit_transform(df['city'])
df['has_covid'] = le.fit_transform(df['has_covid'])

In [53]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
lr = LogisticRegression()

In [58]:
lr.fit(x_train, y_train)

LogisticRegression()

In [59]:
y_pred = lr.predict(x_test)

In [65]:
from sklearn.metrics import accuracy_score

In [66]:
accuracy_score(y_test, y_pred)

0.75

In [67]:
# -- On atteration data

In [69]:
df = pd.read_csv("/content/Attrition - Attrition.csv")
df.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7

In [71]:
# df.isna().sum()

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   int64
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   int64
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   int64
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   int64
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   int64
 22  OverTime                  1470 non-null   int64
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(35)
memory usage: 402.1 KB

In [73]:
from sklearn.preprocessing import LabelEncoder

In [74]:
le = LabelEncoder()

In [75]:

cat = df.select_dtypes(include='object').columns

In [76]:
for i in cat:
  df[i]=le.fit_transform(df[i])

In [78]:
x = df.drop(columns=['Attrition'])
y = df['Attrition']

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [81]:
from sklearn.linear_model import LogisticRegression

In [82]:
lr = LogisticRegression()

In [83]:
lr.fit(x_train, y_train )

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [84]:
y_pred = lr.predict(x_test)

In [85]:
from sklearn.metrics import accuracy_score

In [86]:
accuracy_score(y_test, y_pred)

0.8673469387755102